# Generated by Django 5.1.7 on 2025-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listing_image_1_listing_image_2_listing_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
