# Generated by Django 5.1.7 on 2025-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='additional_info_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
