# Generated by Django 5.1.7 on 2025-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_khetsinguser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khetsinguser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
